apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-nfs-export-dynamic
spec:
  replicas: 1
  selector:
    matchLabels:
      name: deployment-nfs-export-dynamic
  strategy:
    type: Recreate
  template:
    metadata:
      name: deployment-nfs-export-dynamic
      labels:
        name: deployment-nfs-export-dynamic
    spec:
      nodeSelector:
        "kubernetes.io/os": linux
      terminationGracePeriodSeconds: 0
      containers:
        - name: deployment-nfs-export-dynamic
          image: daocloud.io/nginx
          command:
            - "/bin/bash"
            - "-c"
            - set -euo pipefail; while true; do echo $(hostname) $(date) >> /mnt/nfs/outfile; sleep 1; done
          volumeMounts:
            - name: nfs
              mountPath: "/mnt/nfs"
      volumes:
        - name: nfs
          persistentVolumeClaim:
            claimName: pvc-nfs-export-dynamic
